"""create character_details

Revision ID: 2fbf1fe9efdb
Revises: 
Create Date: 2025-08-06 23:05:30.002185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fbf1fe9efdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters_details', sa.Column('character_avatar_url', sa.Text(), nullable=True))
    op.add_column('characters_details', sa.Column('character_voice_url', sa.Text(), nullable=True))
    op.add_column('characters_details', sa.Column('delete_msg', sa.String(), nullable=True))
    op.add_column('characters_details', sa.Column('deletedon', sa.DateTime(), nullable=True))
    op.alter_column('characters_details', 'addedon',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters_details', 'modifiedon',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('characters_details', 'likes_control')
    op.drop_column('characters_details', 'avatar_url')
    op.drop_column('characters_details', 'deleteon')
    op.drop_column('characters_details', 'voice_sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters_details', sa.Column('voice_sample', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('characters_details', sa.Column('deleteon', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('characters_details', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('characters_details', sa.Column('likes_control', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('characters_details', 'modifiedon',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('characters_details', 'addedon',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('characters_details', 'deletedon')
    op.drop_column('characters_details', 'delete_msg')
    op.drop_column('characters_details', 'character_voice_url')
    op.drop_column('characters_details', 'character_avatar_url')
    # ### end Alembic commands ###
