"""add character_id and foreign keys

Revision ID: 385d1d3f6ac7
Revises: 2fbf1fe9efdb
Create Date: 2025-10-02 23:44:31.261770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '385d1d3f6ac7'
down_revision: Union[str, Sequence[str], None] = '2fbf1fe9efdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_gender')
    op.create_foreign_key(None, 'chat_history', 'members', ['member_id'], ['id'])
    op.create_foreign_key(None, 'chat_history', 'characters_details', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_table('character_gender',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('addedon', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifiedon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delete_msg', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('character_gender_pkey'))
    )
    # ### end Alembic commands ###
